# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Michael Harrison"
email: "hello@michaelharrison.party"
description: > # this means to ignore newlines until the next setting
  Web Developer & Wooden Spoon Aficionado.
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://michaelharrison.party" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#Ruby Gems
gems:
  - jemoji

#Custom config
social_media:
  github:
    url: "http://www.github.com/"
    username: "harrim91"
    fa-icon: "fa-github-alt"
  linkedin:
    url: "http://www.linkedin.com/in/"
    username: "mharrison3"
    fa-icon: "fa-linkedin"
  twitter:
    url: "http://www.twitter.com/"
    username: "mikeh91"
    fa-icon: "fa-twitter"
