# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Harrison
email: harrim91@hotmail.co.uk
description: > # this means to ignore newlines until the next setting
  Web Developer & Wooden Spoon Aficionado.
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://michaelharrison.party" # the base hostname & protocol for your site
twitter_username: mikeh91
github_username:  harrim91

# Build settings
markdown: kramdown

#Ruby Gems
gems:
  - jemoji
